name: iOS Deploy to TestFlight

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Ruby environment to use Fastlane
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Choose a suitable Ruby version for your environment

    # Install Fastlane
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      working-directory: ./fastlane

    # Setup Fastlane and match from scratch
    - name: Fastlane Init and Match
      env:
        FASTLANE_USER: ${{ secrets.APPLE_DEVELOPER_USERNAME }}               # Your Apple ID
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }} # Your Apple Application Specific Password
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}         # Password for your match repository
      run: |
        # Initialize Fastlane
        bundle exec fastlane init

        # Setup match
        bundle exec fastlane match init
        # bundle exec fastlane match development
        bundle exec fastlane match appstore
      working-directory: ./fastlane

    # Build and deploy the app to TestFlight
    - name: Build and Upload to TestFlight
      env:
        FASTLANE_USER: ${{ secrets.APPLE_ID }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: |
        bundle exec fastlane match appstore
        bundle exec fastlane build
        bundle exec fastlane pilot upload
      working-directory: ./fastlane
