name: Build and Deploy to TestFlight

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        if ! command -v aws &> /dev/null
        then
          echo "AWS CLI not found, installing..."
          brew install awscli
        else
          echo "AWS CLI already installed"
        fi

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION

    - name: Set up Fastlane
      run: |
        gem install fastlane

    - name: Set up Matchfile
      env:
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        S3_REGION: ${{ secrets.S3_REGION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPLE_DEVELOPER_USERNAME: ${{ secrets.APPLE_DEVELOPER_USERNAME }}
      run: |
        echo 'storage_mode("s3")' > Matchfile
        echo 's3_bucket("$S3_BUCKET_NAME")' >> Matchfile
        echo 's3_region("$S3_REGION")' >> Matchfile
        echo 'type("appstore")' >> Matchfile
        echo 'app_identifier("com.yourcompany.yourapp")' >> Matchfile
        echo 'username("$APPLE_DEVELOPER_USERNAME")' >> Matchfile

    - name: Sync Certificates and Provisioning Profiles
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: |
        fastlane match appstore --type appstore

    - name: Build and upload to TestFlight
      env:
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: |
        fastlane ios beta

    - name: Clean up
      run: |
        rm -f Matchfile
