name: iOS CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Specify version type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build-and-deploy:
    runs-on: macos-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    env:
      APP_IDENTIFIER: com.thinksys.covid
      APPLE_DEVELOPER_ACCOUNT: ${{ secrets.APPLE_DEVELOPER_ACCOUNT }}
      FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      API_KEY_ID: ${{ secrets.FASTLANE_API_KEY_ID }}
      API_ISSUER_ID: ${{ secrets.FASTLANE_API_ISSUER_ID }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      FASTLANE_API_KEY_PATH: ${{ secrets.FASTLANE_API_KEY_PATH }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
      FASTLANE_API_KEY_KEY_ID: ${{ secrets.FASTLANE_API_KEY_KEY_ID }}
      FASTLANE_API_KEY_ISSUER_ID: ${{ secrets.FASTLANE_API_KEY_ISSUER_ID }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        gem install fastlane
        gem install fastlane-plugin-versioning

    - name: Set up Apple Developer API Key
      run: |
        echo '{
          "key_id": "${{ secrets.FASTLANE_API_KEY_KEY_ID }}",
          "issuer_id": "${{ secrets.FASTLANE_API_KEY_ISSUER_ID }}",
          "key_content": "${{ secrets.FASTLANE_API_KEY_P8 }}"
        }' > api_key.json
        echo "${{ secrets.FASTLANE_API_KEY_P8 }}" > api_key.p8

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION

    - name: Create and unlock keychain
      run: |
        security create-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} /Users/runner/Library/Keychains/ci-temp.keychain-db
        security unlock-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} /Users/runner/Library/Keychains/ci-temp.keychain-db
        security list-keychains -s /Users/runner/Library/Keychains/ci-temp.keychain-db
        security default-keychain -s /Users/runner/Library/Keychains/ci-temp.keychain-db
        security set-keychain-settings -t 3600 -l /Users/runner/Library/Keychains/ci-temp.keychain-db

    - name: Create Dynamic Fastlane Configuration
      run: |
        mkdir -p ./fastlane
        cat <<EOF > ./fastlane/Appfile
        apple_id("${{ secrets.FASTLANE_APPLE_ID }}")
        team_id("${{ secrets.TEAM_ID }}")
        itc_team_id("${{ secrets.ITC_TEAM_ID }}")
        app_identifier("${{ env.APP_IDENTIFIER }}")
        EOF

        cat <<EOF > ./fastlane/Matchfile
        s3_bucket("${{ secrets.S3_BUCKET_NAME }}")
        storage_mode("s3")
        type("appstore")
        app_identifier(["${{ env.APP_IDENTIFIER }}"])
        username("${{ secrets.FASTLANE_APPLE_ID }}")
        EOF

        cat <<EOF > ./fastlane/Fastfile
        default_platform(:ios)

        platform :ios do
          desc "Build and deploy to TestFlight"
          lane :beta do
            api_key = app_store_connect_api_key(
                key_id: "${{ secrets.FASTLANE_API_KEY_KEY_ID }}",
                issuer_id: "${{ secrets.FASTLANE_API_KEY_ISSUER_ID }}",
                key_content: "${{ secrets.FASTLANE_API_KEY_P8 }}"
            )

            version = get_app_store_version_number(bundle_id: 'com.thinksys.covid')
            puts "Checking AppStore version number set: #{version}"
            

            # Ensure a valid version number is set
            current_version = get_version_number(xcodeproj: "Xcode Demo.xcodeproj")
            puts "New version number set: #{current_version}"
            
            if current_version.empty? || !current_version.match?(/^\d+(\.\d+)*$/)
              puts "Current version is invalid or empty. Setting default version to 1.0.0"
              increment_version_number(
                version_number: "1.0.0",
                xcodeproj: "Xcode Demo.xcodeproj"
              )
            end

            # Increment version number based on version_type input
            bump_type = ENV['VERSION_TYPE'] || 'patch'
            increment_version_number(
              bump_type: bump_type,
              xcodeproj: "Xcode Demo.xcodeproj"
            )

            new_version = get_version_number(xcodeproj: "Xcode Demo.xcodeproj")
            puts "New version number set: #{new_version}"
            


            # Fetch the latest build number from App Store Connect
            latest_build_number = nil
            begin
            latest_build_number = app_store_build_number(
              api_key: api_key,
              app_identifier: ENV['APP_IDENTIFIER'],
              live: false,
            )
             puts "Latest build number fetched from App Store: #{latest_build_number}"
           rescue => e
             puts "No existing build found, starting with build number 1"
           end

           # Determine the new build number
           new_build_number = (latest_build_number.nil? ? 1 : latest_build_number.to_i + 1)
           puts "New build number calculated: #{new_build_number}"
          
            # Update build number in Xcode project
            increment_build_number(
              build_number: new_build_number.to_s,
            )
            puts "New build number set: #{new_build_number}"
            
            # Use match for provisioning profiles and certificates
            match(
                type: "appstore",
                readonly: false,
                api_key: api_key,
                team_id: "${{ secrets.TEAM_ID }}",
                keychain_name: "ci-temp.keychain-db",
                keychain_password: "${{ secrets.KEYCHAIN_PASSWORD }}"
            )

            # Build the app
            build_app(
              scheme: "Xcode Demo",
              codesigning_identity: "Apple Distribution"
            )

            # Upload to TestFlight
            upload_to_testflight(
              username: ENV['FASTLANE_APPLE_ID'],
              skip_waiting_for_build_processing: true,
              app_identifier: ENV['APP_IDENTIFIER']
            )

            # Delete temp keychain
            delete_keychain(name: "ci-temp.keychain")
          end
        end
        EOF

    - name: Build and Deploy to TestFlight
      env:
        VERSION_TYPE: ${{ github.event.inputs.version_type }}
      run: bundle exec fastlane ios beta

    - name: Notify Success
      if: success()
      run: echo "iOS Application successfully released to TestFlight."
